name: "BentoPDF"
description: "Privacy-first client-side PDF toolkit!"
url: https://github.com/alam00000/bentopdf
version: "2.2.1"
slug: bentopdf
init: false
arch:
  - aarch64
  - amd64
ports:
  3000/tcp: 3000
image: ghcr.io/bvgorp/bentopdf-{arch}
# ingress: true
# panel_icon: mdi:file-pdf-box
